### ISSUE TITLE
Support for Safari

### ISSUE THREAD

**Issue by MrBTTF** [figo-connect/figo_jwe_example#2]
Is there any solution to make encryption work on safari?

**Comment by berend** [comment]
we are using webcrypto-shim to support browser that don't have a webcrypto api, see [here](https://github.com/vibornoff/webcrypto-shim#supported-browsers).

Can give us some error messages that show, what is not working? Also Safari version would be nice.

**Comment by MrBTTF** [comment]
Thanks for reply. The problem was fixed. The error was
![bank_connect_safari](https://user-images.githubusercontent.com/5940255/34481657-05b9d2d8-efbc-11e7-8363-10a89ef2ce33.png)
I have replaced webcrypto-shim for [webcrypto-liner](https://github.com/PeculiarVentures/webcrypto-liner) library.
